name: Release

on:
  release:
    types: [created]

permissions:
  id-token: write
  contents: write

jobs:
  ci:
    name: Call CI
    uses: ./.github/workflows/ci.yml

  publish:
    runs-on: ubuntu-latest
    needs: ci
    environment:
      name: release
      url: https://pypi.org/project/varpy/

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Setup the environment
        uses: ./.github/actions/build_env
  
      - name: Build package
        run: uv build

      - name: Publish package distributions to PyPI
        run: uv publish

      - name: Sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3.0.1
        with:
          inputs: >-
            dist/*.tar.gz
            dist/*.whl

      - name: Upload distribution files
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}